/**
 * metadata.ts — Centralized metadata generation for all tool responses.
 *
 * Provides professional-use warnings, data freshness tracking, and source authority disclosure.
 */

import type { Database } from '@ansvar/mcp-sqlite';

export interface ResponseMetadata {
  /** Data freshness information */
  data_freshness: DataFreshness;

  /** Professional use disclaimer */
  disclaimer: string;

  /** Source authority disclosure */
  source_authority: SourceAuthority;

  /** Known coverage gaps */
  coverage_gaps: string[];

  /** EU AI Act transparency notice */
  ai_disclosure: string;

  /** Optional note (e.g. document resolution failure) */
  note?: string;

  /** Query strategy used (e.g. 'broadened', 'like_fallback') */
  query_strategy?: string;
}

export interface DataFreshness {
  /** Last database update timestamp */
  last_ingested: string | null;

  /** Warning if data appears stale (>30 days) */
  staleness_warning: string | null;
}

export interface SourceAuthority {
  /** Primary data source description */
  primary_source: string;

  /** Authority level assessment */
  authority_level: 'official' | 'community-maintained';

  /** Verification requirement */
  verification_required: string;
}

/**
 * Generate standard metadata for tool responses.
 *
 * @param db - Optional database handle. If not provided, data freshness checks are skipped.
 */
export function generateResponseMetadata(db?: Database): ResponseMetadata {
  const dataFreshness = db ? getDataFreshness(db) : getEmptyDataFreshness();
  const sourceAuthority = getSourceAuthority();

  return {
    data_freshness: dataFreshness,
    disclaimer: 'NOT LEGAL ADVICE. This tool is for research purposes only and does not constitute professional legal advice. Always verify citations with official sources before relying on them in legal matters. Users are solely responsible for verifying accuracy and currency of all information.',
    source_authority: sourceAuthority,
    coverage_gaps: [
      'Full text of Proposisjoner (hosted on regjeringen.no — only metadata and titles stored here)',
      'Historical sessions prior to 2022-2023 (v0.1 sample only)',
      'Representantforslag (private member bills)',
      'Meldinger (white papers)',
      'EU Regulations and Directives',
      'Legal commentary and annotations'
    ],
    ai_disclosure: 'AI-assisted legal research tool. Results generated by algorithmic search and may contain errors or omissions. Human review required before professional use.'
  };
}

/**
 * Return empty data freshness when database is not available.
 */
function getEmptyDataFreshness(): DataFreshness {
  return {
    last_ingested: null,
    staleness_warning: 'Data freshness information unavailable (tool does not query database)'
  };
}

/**
 * Check data freshness and generate staleness warnings.
 */
function getDataFreshness(db: Database): DataFreshness {
  let lastIngested: string | null = null;
  try {
    const row = db.prepare(`
      SELECT MAX(tilgjengelig_dato) as max_date
      FROM preparatory_works
      WHERE tilgjengelig_dato IS NOT NULL
    `).get() as { max_date: string | null } | undefined;
    lastIngested = row?.max_date || null;
  } catch {
    // Ignore errors — table may not exist
  }

  const stalenessWarning = calculateStalenessWarning(lastIngested);

  return {
    last_ingested: lastIngested,
    staleness_warning: stalenessWarning
  };
}

/**
 * Generate staleness warning if data is >90 days old.
 */
function calculateStalenessWarning(lastDate: string | null): string | null {
  if (!lastDate) {
    return 'Ingestion timestamp unavailable';
  }

  const now = new Date();
  const ninetyDaysAgo = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
  const lastTimestamp = new Date(lastDate);

  if (lastTimestamp < ninetyDaysAgo) {
    const daysOld = Math.floor((now.getTime() - lastTimestamp.getTime()) / (24 * 60 * 60 * 1000));
    return `Preparatory works data is ${daysOld} days old — new sessions may be missing`;
  }

  return null;
}

/**
 * Get source authority disclosure.
 */
function getSourceAuthority(): SourceAuthority {
  return {
    primary_source: 'data.stortinget.no (official Stortinget API) — Proposisjoner and Innstillinger under NLOD 2.0',
    authority_level: 'official',
    verification_required: 'ALWAYS cross-check with official sources (stortinget.no or regjeringen.no) before using in professional legal work.'
  };
}

/**
 * Wrapper type for tool responses that includes metadata.
 */
export interface ToolResponse<T> {
  /** Tool-specific results */
  results: T;

  /** Professional-use metadata and warnings */
  _meta: ResponseMetadata;

  /** Citation metadata for deterministic citation pipeline (optional) */
  _citation?: import('./citation.js').CitationMetadata;

  /** Truncation hint (optional) */
  _truncated?: boolean;
  _hint?: string;
}
